# Generated by Django 4.0.5 on 2022-06-05 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=70, unique=True, verbose_name='Username')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('date_joined', models.DateTimeField(auto_now=True, verbose_name='Data joined')),
                ('is_active', models.BooleanField(default=False, verbose_name='Activity status')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Verified status')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Staff')),
            ],
        ),
    ]
