# Generated by Django 4.0.5 on 2022-06-23 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteuser',
            name='activation_code',
            field=models.CharField(blank=True, max_length=200, unique=True),
        ),
    ]
