# Generated by Django 4.0.5 on 2022-06-05 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invite_code', models.CharField(max_length=70, unique=True, verbose_name='invite code')),
                ('invited_by', models.CharField(max_length=70, unique=True, verbose_name='Invited by')),
                ('points', models.IntegerField(default=0, verbose_name='Points')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='login.usercode'),
        ),
    ]
