# Generated by Django 4.0.5 on 2022-06-05 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_usercode_user_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='info',
        ),
        migrations.AddField(
            model_name='user',
            name='invite_code',
            field=models.CharField(blank=True, max_length=70, unique=True, verbose_name='invite code'),
        ),
        migrations.AddField(
            model_name='user',
            name='invited_by',
            field=models.CharField(blank=True, max_length=70, unique=True, verbose_name='Invited by'),
        ),
        migrations.AddField(
            model_name='user',
            name='points',
            field=models.IntegerField(default=0, verbose_name='Points'),
        ),
        migrations.DeleteModel(
            name='UserCode',
        ),
    ]
