# Generated by Django 4.0.5 on 2022-06-06 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_remove_user_info_user_invite_code_user_invited_by_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='SiteUser',
        ),
    ]
