# Generated by Django 4.0.5 on 2022-06-06 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_rename_user_siteuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteuser',
            name='invited_by',
        ),
        migrations.AddField(
            model_name='siteuser',
            name='personal_invite_code',
            field=models.CharField(blank=True, max_length=70, unique=True, verbose_name='invite code'),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='invite_code',
            field=models.CharField(blank=True, max_length=70, verbose_name='Invited by'),
        ),
    ]
