# Generated by Django 4.0.5 on 2022-06-06 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_remove_siteuser_invited_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteuser',
            name='invite_code',
            field=models.CharField(blank=True, max_length=70, verbose_name='Invite code'),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='personal_invite_code',
            field=models.CharField(max_length=70, verbose_name='Personal invite code'),
        ),
    ]
